In [25]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Doğrusal-Denklemler" data-toc-modified-id="Doğrusal-Denklemler-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Doğrusal Denklemler</a></span><ul class="toc-item"><li><span><a href="#Vektör" data-toc-modified-id="Vektör-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Vektör</a></span></li><li><span><a href="#Matris" data-toc-modified-id="Matris-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Matris</a></span></li><li><span><a href="#Matris-Çarpımı" data-toc-modified-id="Matris-Çarpımı-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Matris Çarpımı</a></span></li><li><span><a href="#Doğrusal-Denklem" data-toc-modified-id="Doğrusal-Denklem-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Doğrusal Denklem</a></span></li></ul></li></ul></div>

# Doğrusal Denklemler

In [26]:
import pandas as pd
import numpy as np

## Vektör

In [29]:
v=np.array([1,2])
v

array([1, 2])


##  Matris

In [30]:
m= np.array([[2,3],[5,7],[8,9]])
m

array([[2, 3],
       [5, 7],
       [8, 9]])

##  Matris Çarpımı

In [31]:
m.dot(v)

array([ 8, 19, 26])

SpreadSheet Örnek

In [32]:
A= np.array([   [1,9,10,5,8],
                [6,7,5,7,10],
                [7,5,10,3,3],
                [5,9,10,6,9],
                [1,7,10,10,8],
                [8,10,7,6,8],
                [10,5,9,4,6],
                [4,9,10,7,1],
                [7,4,6,8,3]  ])
A

array([[ 1,  9, 10,  5,  8],
       [ 6,  7,  5,  7, 10],
       [ 7,  5, 10,  3,  3],
       [ 5,  9, 10,  6,  9],
       [ 1,  7, 10, 10,  8],
       [ 8, 10,  7,  6,  8],
       [10,  5,  9,  4,  6],
       [ 4,  9, 10,  7,  1],
       [ 7,  4,  6,  8,  3]])

In [33]:
A.shape

(9, 5)

In [34]:
B=np.array([   [5,9,3,1,10,8,6,6,2],
                [5,8,2,5,9,5,10,8,7],
                [7,8,4,9,5,5,5,7,7],
                [3,3,5,2,10,7,8,9,4],
                [9,9,9,4,3,9,1,4,7],])
B

array([[ 5,  9,  3,  1, 10,  8,  6,  6,  2],
       [ 5,  8,  2,  5,  9,  5, 10,  8,  7],
       [ 7,  8,  4,  9,  5,  5,  5,  7,  7],
       [ 3,  3,  5,  2, 10,  7,  8,  9,  4],
       [ 9,  9,  9,  4,  3,  9,  1,  4,  7]])

In [35]:
B.shape

(5, 9)

In [36]:
A.dot(B)

array([[207, 248, 158, 178, 215, 210, 194, 225, 211],
       [211, 261, 177, 140, 248, 247, 197, 230, 194],
       [166, 219, 113, 140, 204, 179, 169, 191, 152],
       [239, 296, 184, 188, 268, 258, 227, 262, 230],
       [212, 247, 179, 178, 247, 235, 214, 254, 217],
       [229, 298, 174, 165, 289, 263, 239, 263, 215],
       [204, 268, 150, 148, 248, 232, 193, 223, 176],
       [165, 218, 114, 157, 244, 185, 221, 233, 176],
       [148, 194, 120, 109, 225, 189, 179, 200, 137]])

Pandas

In [37]:
A=pd.DataFrame(A)
A

0   1   2   3   4
0   1   9  10   5   8
1   6   7   5   7  10
2   7   5  10   3   3
3   5   9  10   6   9
4   1   7  10  10   8
5   8  10   7   6   8
6  10   5   9   4   6
7   4   9  10   7   1
8   7   4   6   8   3

In [11]:
B=pd.DataFrame(B)
B

0  1  2  3   4  5   6  7  8
0  5  9  3  1  10  8   6  6  2
1  5  8  2  5   9  5  10  8  7
2  7  8  4  9   5  5   5  7  7
3  3  3  5  2  10  7   8  9  4
4  9  9  9  4   3  9   1  4  7

In [12]:
A.dot(B)

0    1    2    3    4    5    6    7    8
0  207  248  158  178  215  210  194  225  211
1  211  261  177  140  248  247  197  230  194
2  166  219  113  140  204  179  169  191  152
3  239  296  184  188  268  258  227  262  230
4  212  247  179  178  247  235  214  254  217
5  229  298  174  165  289  263  239  263  215
6  204  268  150  148  248  232  193  223  176
7  165  218  114  157  244  185  221  233  176
8  148  194  120  109  225  189  179  200  137

## Doğrusal Denklem

In [41]:

class DoğrusalDenklem():

    def __init__(self,A,b):
        self.denklem=np.concatenate((A,b),axis=1)
        self.satır_sayısı=self.denklem.shape[0]
        self.sütün_sayısı=self.denklem.shape[1]

    def __str__(self):
        return "Denklem sistemi ----> \n {Ab}".format(Ab=self.denklem)

    def __len__(self):
        return self.denklem.shape[0]

    def __del__(self):
        return  "Doğrusal denklem silinmiştir."

    def GaussJordan(self):
        """
        Gauss Jordan metodu ile satır işlemleri yapıp, değişkenleri
        hesaplar.Öncelikle katsayı matrisi ile sonuç matrisi birleştirilir.
        İlk olarak köşegen elemanın 0'a eşitliği kontrol edilir.
        Daha sonrasında ona ait sütündaki diğer elemanlar 0 olacak
        şekilde satır işlemleri yapılır. Bütün satırların üzerinden
        bu yöntemle geçilir.

        """

        # Adım 1 : A|b matrisini oluştur.

        Ab=self.denklem.copy()
        Ab=Ab.astype(float)
        satır_sayısı=Ab.shape[0]
        sutun_sayısı=Ab.shape[1]

        for i in range(satır_sayısı): # Bütün satırlar için yapılacaktır.
            if Ab[i][i]==0:  # Satırdaki köşegen eleman 0 ise onu değiştirmek gereklidir.
                Geçici=Ab[i].copy()
                satır_indisleri=[a for a in range(i,satır_sayısı) if Ab[a][i]!=0]
                if satır_indisleri:
                    Ab[i]=Ab[satır_indisleri[0]].copy()
                    Ab[satır_indisleri[0]]=Geçici
                else:
                    print(str(i)+". satırından sonra işlem yapılamamaktadır")
                    return Ab
            Ab[i]=Ab[i]/Ab[i][i] # Köşegen katsayısına bölüyoruz.
            for s in range(satır_sayısı):
                if i==s:
                    pass
                else:
                    Ab[s]=Ab[s]-Ab[i]*Ab[s][i] # Bir satırı diğerinden çıkartarak köşegen alt kısımlarını sıfıra eşitliyoruz.

        return Ab

    def çözüm_durumu(self):
        çözüm=self.GaussJordan()
        satır_sayısı=self.satır_sayısı
        sutun_sayısı= self.sütün_sayısı
        tekÇözüm=False

        for i in range(satır_sayısı):
            if all(çözüm[i,:sutun_sayısı-1]==0) and çözüm[i,sutun_sayısı-1]!=0:
                return "çözümsüz"

        if satır_sayısı==(sutun_sayısı-1):
            i=0
            while i<satır_sayısı and çözüm[i][i]==1:
                i+=1

            if i==satır_sayısı:
                tekÇözüm=True
                return "tek"
        else:
            return "sonsuz"

    def rank_sayar(self):
        Ab=self.GaussJordan()
        say=0
        satır_sayısı=Ab.shape[0]
        for i in range(satır_sayısı):
               if Ab[i][i]==1 and Ab[:,i].sum()==1:
                    say+=1
        return say

    def doğrusal_bağımsız(self):
        Ab=self.GaussJordan()
        rank=self.rank_sayar()
        m=Ab.shape[0]
        if m==rank:
            return True
        elif m>rank:
            return False
        else:
            return "Error"

In [39]:

# 1
A=np.array([[0,2,2 ],[1,2,1 ],[0,1,-1 ]],float)
df_A=pd.DataFrame(A);df_A

0    1    2
0  0.0  2.0  2.0
1  1.0  2.0  1.0
2  0.0  1.0 -1.0

In [40]:
b=np.array([[4],[4],[0]],float)
df_b=pd.DataFrame(b);df_b

0
0  4.0
1  4.0
2  0.0

In [42]:
denklem=DoğrusalDenklem(A,b)


In [44]:
print(denklem)

Denklem sistemi ----> 
 [[ 0.  2.  2.  4.]
 [ 1.  2.  1.  4.]
 [ 0.  1. -1.  0.]]


In [45]:
denklem.GaussJordan()

array([[ 1.,  0.,  0.,  1.],
       [ 0.,  1.,  0.,  1.],
       [-0., -0.,  1.,  1.]])

In [17]:
denklem.çözüm_durumu()

'tek'

In [46]:
# 2
A=np.array([[0,0,0,0,1],
            [0,0,1,-1,0],
            [1,0,0,0,1],
            [0,7,-8,0,0],
            [2,0,0,0,0]],float)
A

array([[ 0.,  0.,  0.,  0.,  1.],
       [ 0.,  0.,  1., -1.,  0.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 0.,  7., -8.,  0.,  0.],
       [ 2.,  0.,  0.,  0.,  0.]])

In [47]:
b=np.array([[-4 ],[ 3 ],[ 3 ],[-14 ],[2]],float)

denklem=DoğrusalDenklem(A,b)
denklem.GaussJordan()


3. satırından sonra işlem yapılamamaktadır


array([[ 1.        ,  0.        ,  0.        ,  0.        ,  1.        ,
         3.        ],
       [ 0.        ,  1.        ,  0.        , -1.14285714,  0.        ,
         1.42857143],
       [ 0.        ,  0.        ,  1.        , -1.        ,  0.        ,
         3.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ,
        -4.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        , -2.        ,
        -4.        ]])

In [20]:
denklem.çözüm_durumu()

3. satırından sonra işlem yapılamamaktadır


In [48]:
A=np.array([[1,1,0 ],[0,-1,2 ],[0,1,1 ]],float)
b=np.array([[2],[3],[3]],float)
denklem=DoğrusalDenklem(A,b)
denklem.GaussJordan()

array([[1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [0., 0., 1., 2.]])

In [22]:
denklem.çözüm_durumu()


'tek'

In [49]:
np.linalg.solve(A,b)

array([[1.],
       [1.],
       [2.]])

In [23]:
np.linalg.solve(A,b)

array([[1.],
       [1.],
       [2.]])

In [24]:
np.linalg.inv(A).dot(b)


array([[1.],
       [1.],
       [2.]])