In [7]:
import pandas as pd
import numpy as np

Vektör

In [8]:
v=np.array([1,2])
v

array([1, 2])


Matris

In [9]:
m= np.array([[2,3],[5,7]])
m

array([[2, 3],
       [5, 7]])

Matris Çarpımı

In [10]:
m.dot(v)

array([ 8, 19])

SpreadSheet Örnek

In [11]:
A= np.array([   [1,9,10,5,8],
                [6,7,5,7,10],
                [7,5,10,3,3],
                [5,9,10,6,9],
                [1,7,10,10,8],
                [8,10,7,6,8],
                [10,5,9,4,6],
                [4,9,10,7,1],
                [7,4,6,8,3]  ])
A

array([[ 1,  9, 10,  5,  8],
       [ 6,  7,  5,  7, 10],
       [ 7,  5, 10,  3,  3],
       [ 5,  9, 10,  6,  9],
       [ 1,  7, 10, 10,  8],
       [ 8, 10,  7,  6,  8],
       [10,  5,  9,  4,  6],
       [ 4,  9, 10,  7,  1],
       [ 7,  4,  6,  8,  3]])

In [12]:
A.shape

(9, 5)

In [13]:
B=np.array([   [5,9,3,1,10,8,6,6,2],
                [5,8,2,5,9,5,10,8,7],
                [7,8,4,9,5,5,5,7,7],
                [3,3,5,2,10,7,8,9,4],
                [9,9,9,4,3,9,1,4,7],])
B

array([[ 5,  9,  3,  1, 10,  8,  6,  6,  2],
       [ 5,  8,  2,  5,  9,  5, 10,  8,  7],
       [ 7,  8,  4,  9,  5,  5,  5,  7,  7],
       [ 3,  3,  5,  2, 10,  7,  8,  9,  4],
       [ 9,  9,  9,  4,  3,  9,  1,  4,  7]])

In [14]:
B.shape

(5, 9)

In [15]:
A.dot(B)

array([[207, 248, 158, 178, 215, 210, 194, 225, 211],
       [211, 261, 177, 140, 248, 247, 197, 230, 194],
       [166, 219, 113, 140, 204, 179, 169, 191, 152],
       [239, 296, 184, 188, 268, 258, 227, 262, 230],
       [212, 247, 179, 178, 247, 235, 214, 254, 217],
       [229, 298, 174, 165, 289, 263, 239, 263, 215],
       [204, 268, 150, 148, 248, 232, 193, 223, 176],
       [165, 218, 114, 157, 244, 185, 221, 233, 176],
       [148, 194, 120, 109, 225, 189, 179, 200, 137]])

Pandas

In [16]:
A=pd.DataFrame(A)
A

0   1   2   3   4
0   1   9  10   5   8
1   6   7   5   7  10
2   7   5  10   3   3
3   5   9  10   6   9
4   1   7  10  10   8
5   8  10   7   6   8
6  10   5   9   4   6
7   4   9  10   7   1
8   7   4   6   8   3

In [17]:
B=pd.DataFrame(B)
B

0  1  2  3   4  5   6  7  8
0  5  9  3  1  10  8   6  6  2
1  5  8  2  5   9  5  10  8  7
2  7  8  4  9   5  5   5  7  7
3  3  3  5  2  10  7   8  9  4
4  9  9  9  4   3  9   1  4  7

In [18]:
A.dot(B)

0    1    2    3    4    5    6    7    8
0  207  248  158  178  215  210  194  225  211
1  211  261  177  140  248  247  197  230  194
2  166  219  113  140  204  179  169  191  152
3  239  296  184  188  268  258  227  262  230
4  212  247  179  178  247  235  214  254  217
5  229  298  174  165  289  263  239  263  215
6  204  268  150  148  248  232  193  223  176
7  165  218  114  157  244  185  221  233  176
8  148  194  120  109  225  189  179  200  137